### ISSUE TITLE
cannot receive packet

### ISSUE THREAD

**Issue by XgamiX** [MrKinau/FishingBot#101]
when i try to connect it says cannot receive packet

**Comment by MrKinau** [comment]
This may have several reasons. Can you enabled logs -> log packets and restart the bot. Then send us your (logs/log0.log) to let us have a look whats wrong wtih it.

**Comment by XgamiX** [comment]
> This may have several reasons. Can you enabled logs -> log packets and restart the bot. Then send us your (logs/log0.log) to let us have a look whats wrong with it.

[log0.log](https://github.com/MrKinau/FishingBot/files/5584086/log0.log)

**Comment by MrKinau** [comment]
Well, this log does not have the option set. Maybe it's log0.log.1, lo0.log.2, search for those logs and check if it contains something like this: "[PLAY] |C| <<<"

**Comment by MrKinau** [comment]
As you havent answered for 48 hours, I apologize this issue is no longer in interest. If it still ist valid, please send a log of the issue, as instructed before.
