### ISSUE TITLE
Ingame Inventory menu

### ISSUE THREAD

**Issue by hendrikbgr** [MrKinau/FishingBot#111]
The server I want to use this tool one requires the use to click an item in an inventory menu which pops up upon joining. Is that a way I can make the bot select a certain option? sadly the server had no command to join one of the worlds.

**Comment by MrKinau** [comment]
Currently it is not possible to make the bot click an item in an inventory, but I'll write it on the todo-list, so it can be a part of the start-actions to click on a certain slot in an opened inventory.

**Comment by hendrikbgr** [comment]
Thanks, that feature would be great. Also maybe add the option to make certain key strokes with certain delays 

Cheers

**Comment by MrKinau** [comment]
This is already planned (at least partly). The bot does is not base on Minecraft, it's just an implementation of some parts of the Minecraft protocol so it does not know about keystrokes, but executing commands (or bot commands) in a timer is already planned.

**Comment by hendrikbgr** [comment]
Aah I see. I am going to keep an eye on future updates then

**Comment by MrKinau** [comment]
Dunno, why this issue isn't closed, all the features suggested here are already released. `/clickinv` and timers as well as `/wait`. Thx for your suggestions :)
