### ISSUE TITLE
Bot drops enchanted books, even when told not to.

### ISSUE THREAD

**Issue by crylicwho** [MrKinau/FishingBot#119]
Hello, i'm using this for getting mending books. However, i removed enchanted books from the items to eject list, and it still dropped it. It might be because i don't fully understand it. There is nothing about it on your wiki. I don't know if items to eject list means that if it's on the list it will eject it or if it won't. Please explain it better.

**Comment by MrKinau** [comment]
Thx for your interest. Can you send you ejection rules to let look over them? Just open the config.json and send the relevant lines or send the whole config, but be aware that it contains your login credentials (remove them before uploading it).

**Comment by crylicwho** [comment]
{
    "announces": {
        "announce-lvl-up-text": "I am level %lvl% now",
        "announce-lvl-up": false,
        "discord": {
            "alert-on-level-update": true,
            "alert-on-respawn": true,
            "alert-on-attack": true,
            "ping-on-enchantment": {
                "enchantments": [
                    "MENDING",
                    "UNBREAKING"
                ],
                "items": ["enchanted_book"],
                "enabled": false,
                "mention": "<@USER_ID>"
            },
            "announce-type-discord": "ONLY_ENCHANTED",
            "web-hook": "YOURWEBHOOK",
            "enabled": false
        },
        "announce-type-console": "ALL",
        "announce-type-chat": "NONE"
    },
    "server": {
        "spoof-forge": false,
        "default-protocol": "1.16.4",
        "port": 25565,
        "ip": "127.0.0.1",
        "realm-accept-tos": true,
        "online-mode": true,
        "realm-id": 10696108
    },
    "auto": {
        "auto-eject": {
            "rules": [
                {
                    "name": "fish",
                    "ejectionType": "DROP",
                    "direction": "NORTH",
                    "allowList": [
                        "cod",
                        "salmon",
                        "pufferfish",
                        "tropical_fish"
                    ]
                },
                {
                    "name": "treasure",
                    "ejectionType": "DROP",
                    "direction": "NORTH",
                    "allowList": [
                        "bow",
                        "name_tag",
                        "nautilus_shell",
                        "saddle"
                    ]
                },
                {
                    "name": "junk",
                    "ejectionType": "DROP",
                    "direction": "NORTH",
                    "allowList": [
                        "lily_pad",
                        "bowl",
                        "leather",
                        "leather_boots",
                        "rotten_flesh",
                        "stick",
                        "string",
                        "potion",
                        "bone",
                        "ink_sac",
                        "tripwire_hook"
                    ]
                }
            ],
            "enabled": true
        },
        "auto-command-on-respawn": {
            "delay": 1000,
            "commands": [
                "%prefix%I respawned",
                "/home fishing"
            ],
            "enabled": false
        },
        "auto-reconnect": true,
        "auto-disconnect-players-threshold": 5,
        "auto-quit-before-death": {
            "enabled": false,
            "min-health-before-quit": 6
        },
        "auto-disconnect": false,
        "auto-command-before-death": {
            "min-health-before-death": 6,
            "enabled": false,
            "commands": [
                "%prefix%I am about to die",
                "/home"
            ]
        },
        "auto-reconnect-time": 5,
        "auto-sneak": false
    },
    "start-text": {
        "text": [
            "%prefix%Starting fishing",
            "/trigger Bot"
        ],
        "enabled": true
    },
    "logs": {
        "log-count": 15,
        "log-packets": false
    },
    "account": {
        "password": "",
        "mail": ""
    },
    "misc": {
        "look-speed": 32,
        "prevent-rod-breaking": true,
        "stucking-fix-enabled": true,
        "wiki": "https://github.com/MrKinau/FishingBot/wiki/config",
        "language": "ENGLISH",
        "gui-console-max-lines": 1000,
        "disable-rod-checking": false
    }
}

**Comment by MrKinau** [comment]
Sorry for the long delay.
I've tested the config you sent, but it's completely working for me. Do you had another empty rule, which are used as "everything else"?

**Comment by MrKinau** [comment]
As you haven't answered yet, I assume the problem no longer exists and I'll close the issue.
