### ISSUE TITLE
[Feature request] Passive mode

### ISSUE THREAD

**Issue by abrman** [MrKinau/FishingBot#12]
This feature would allow you to run this in the background (maybe even on a Raspberry Pi), it would passively ping the server to check how many players are online, and if it fits into criteria below a certain amount of players, it will connect and do it's thing :)

settings example:
```
passive-mode=true
passive-player-treshold=3
```

(I'm on a slow server and think I'm only going to be using this while only few people are online to prevent causing lag)

**Comment by MrKinau** [comment]
thank you for this request.

Just for my understanding: You want the bot only to be connected if less than X players are online? And disconnect if this amount (+ the bot) gets exceeded?

**Comment by abrman** [comment]
Exactly :)

**Comment by MrKinau** [comment]
implemented in v2.5 (just edited the release: https://github.com/MrKinau/FishingBot/releases/tag/2.5) thx for requesting, feel free to request more features or report bugs :)
