### ISSUE TITLE
fishingbot suddenly stops working or updating alltogether

### ISSUE THREAD

**Issue by rattaklan** [MrKinau/FishingBot#129]
the bot just suddenly doesnt respond to any input anymore and freezes
![buggy](https://user-images.githubusercontent.com/82901899/115445230-e1b9df80-a215-11eb-8e8e-79f1dc798657.PNG)

**Comment by MrKinau** [comment]
Can you send a log of this incident?

**Comment by rattaklan** [comment]
> Can you send a log of this incident?
[log6.log](https://github.com/MrKinau/FishingBot/files/6346030/log6.log)
[log7.log](https://github.com/MrKinau/FishingBot/files/6346031/log7.log)
[log8.log](https://github.com/MrKinau/FishingBot/files/6346032/log8.log)
[log2.log](https://github.com/MrKinau/FishingBot/files/6346033/log2.log)
[log3.log](https://github.com/MrKinau/FishingBot/files/6346034/log3.log)
[log4.log](https://github.com/MrKinau/FishingBot/files/6346035/log4.log)
[log5.log](https://github.com/MrKinau/FishingBot/files/6346036/log5.log)

**Comment by MrKinau** [comment]
I've updated the latest release with a fix. There were some errors, which occured, because you can fish unusual items on your server (e.g. wooden_sword). Please let me know, if it works for you.

**Comment by rattaklan** [comment]
sure thing thanks mate

**Comment by rattaklan** [comment]
where can i find this fix?

**Comment by MrKinau** [comment]
The latest release: https://github.com/MrKinau/FishingBot/releases/tag/2.7.15

**Comment by rattaklan** [comment]
now it doesnt seem to catch anything at all

**Comment by rattaklan** [comment]
nvm last comment its good

**Comment by MrKinau** [comment]
okay, then I'll close the issue. Just answer if you find any issues.
