### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by Cenetrick** [MrKinau/FishingBot#13]
When i click to open the Fishing Bot java... it makes it seem as if something is loading.. due to the revolving circle next to the mouse.. but nothing happens

**Comment by abrman** [comment]
You don't launch it by double clicking, you launch it like any other java .jar file.
https://www.youtube.com/watch?v=MhwX8_ohOD8

Try following the video. (It's also in the readme)

**Comment by MrKinau** [comment]
Thank you for creating this issue, but as @abrman already said, its not intended to work with a simple doubleclick (There is no GUI). You have to start it viá command line. The video will guide you how to start a java application viá command line. If you still need help of find bugs, you can create a new issue.
