### ISSUE TITLE
Not setting up correctly

### ISSUE THREAD

**Issue by Inferno-Senpai** [MrKinau/FishingBot#143]
I am new to this and I do not know how to set it up on the realm I am on. I read and try to do step by step on the wiki but it still doesn't work. I would like some assistance if need be. I do not know how to get to the file and switch it.

**Comment by MrKinau** [comment]
Please describe the steps you done and send the log to see what's happening. The log can either be found in logs/log0.log or copy and paste the console output in the GUI. The file configuration is no longer needed if you have a display, you can fully use the GUI to manage the bot.
