### ISSUE TITLE
Customizable Webhook Messages

### ISSUE THREAD

**Issue by TheEggi98** [MrKinau/FishingBot#152]
I love the bot and i would wish to customize the webhook messages. 
In Discord i made myself a server just for webhooks and its a bit weird to read

> Warnung bei Levelupdate
> Neues Level erreicht: 

In my opinion it would be better to remove the first line or make it customizable.
But i like that it messages the rod durability too.

![Bild_2021-09-01_131629](https://user-images.githubusercontent.com/55232322/131662251-e04940c4-b440-4a9c-a336-d24389d64ac0.png)

**Comment by MrKinau** [comment]
Thanks for your issue and sorry for the late reply: This is already possible although it's a kind of hacky way to do it, but you can open the jar using an archiving software (e.g. 7zip) and open the lang folder. Inside this folder you'll find the translations files. You can just edit the file of your selected language to modify the messages. In your case it's

**config-announces-discord-alert-on-level-update** and **announce-level-up**
