### ISSUE TITLE
Webhook playerping dont work

### ISSUE THREAD

**Issue by TheEggi98** [MrKinau/FishingBot#153]
The Userid get shown just as plain text.
Which formats i tried:
![image](https://user-images.githubusercontent.com/55232322/131684545-ed74f9a6-10a6-4716-8b92-d1a90f83b4cb.png)
![image](https://user-images.githubusercontent.com/55232322/131684593-920b54ae-b96b-4f6e-8f82-3436da374d3a.png)
![image](https://user-images.githubusercontent.com/55232322/131684621-086274e2-a57f-4ac0-b0a2-4addcbe73008.png)

when i mention me it looks like this:
![image](https://user-images.githubusercontent.com/55232322/131684836-54fecd2b-f616-4230-88f1-eab73b8db24c.png)

**Comment by MrKinau** [comment]
Thanks for your issue and sorry for the late reply,

you have to use the discord user id (described in the [wiki](https://github.com/MrKinau/FishingBot/wiki/Config)).

How to get ther user id: https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-

How to set it up: https://birdie0.github.io/discord-webhooks-guide/other/discord_markdown.html

Basically just use <@123456789> (where 123456789 is your user id)
