### ISSUE TITLE
I can't open .java files even with java, its just crashing for milisecond.

### ISSUE THREAD

**Issue by ApterTheRaptor** [MrKinau/FishingBot#154]
Is there's any way i can fix this or open it right?

**Comment by MrKinau** [comment]
If you want to run it, you need to download the released jar from [here](https://github.com/MrKinau/FishingBot/releases/tag/2.7.17) and execute it as instructed [here](https://github.com/MrKinau/FishingBot/releases/tag/2.7.17)
