### ISSUE TITLE
1.18.2 Support

### ISSUE THREAD

**Issue by kkdlau** [MrKinau/FishingBot#162]
```
[2022-03-02 21:14:12] [SEVERE ] Login failed: {"translate":"multiplayer.disconnect.incompatible","with":["1.18.2"]} 
```

Minecraft 1.18.2 is out and I'm able to connect login and connect to realm. However the above error message keeps popping up. It will be great if the latest version of mc can be supported!

**Comment by MrKinau** [comment]
Thanks for the advise, I've updated the latest release (2.7.18) as well as the proxy testing branch (2.8.0-experimental) to support the new protocol version for MC 1.18.2.

**Comment by kkdlau** [comment]
thx a lot, will there be a release for the latest version?
