### ISSUE TITLE
can you support server with third-party login that uses authlib-injector?

### ISSUE THREAD

**Issue by szdytom** [MrKinau/FishingBot#172]
can you support server with third-party login that uses authlib-injector by add a new auth method? thanks a lot!

**Comment by MrKinau** [comment]
I wont support third party authentication services. You can use OneSix (see [here](https://github.com/MrKinau/FishingBot/wiki#how-can-i-use-the-bot-with-a-3rd-party-launcher-multimcpolymc)) to obtain the Mojang accessToken on any way you want or fork the project and implement your own auth service, but I won't implement support for non-Mojang/MS auth services.
