### ISSUE TITLE
Support for 1.19.51 [REQUEST]

### ISSUE THREAD

**Issue by CarsonD-github** [MrKinau/FishingBot#189]
Add support for Minecraft 1.19.51. Download link is here -> https://www.minecraft.net/download or the server download is here -> https://www.minecraft.net/en-us/download/server

**Comment by CarsonD-github** [comment]
@MrKinau

**Comment by MrKinau** [comment]
There already is 1.19.3 support. Although the chat might not work, everythign else should work: https://github.com/MrKinau/FishingBot/releases/tag/v2.10.4

1.19.51 isnt a minecraft version, but I just assumed you wated 1.19.3 as this is the versions the links pointing to

**Comment by CarsonD-github** [comment]
Ok.
