### ISSUE TITLE
Can I use this on Chromebook

### ISSUE THREAD

**Issue by CarsonD-github** [MrKinau/FishingBot#191]
I am on a Chromebook using Linux (_.deb and .appimage_). Can I use this application?

**Comment by CarsonD-github** [comment]
@MrKinau

**Comment by MrKinau** [comment]
Yes, it's not packaged as a .deb or .appimage, but if you have java installed, you can run it with java. Java is available for ChromeOS

**Comment by CarsonD-github** [comment]
@MrKinau How do I download Java as a .deb or .appimage file?
