### ISSUE TITLE
Bot not working properly on slow server

### ISSUE THREAD

**Issue by Flynn-Mandrake** [MrKinau/FishingBot#20]
I've been getting `[WARNING] Bot is slow (maybe stuck). Trying to restart!` in the console for a while now, and I've been trying to figure out why it keeps happening. What I think is going on is that the server detects that a long while has passed without a fish being caught (because of the slow ping), and then recasts the fishing rod. The issue is that this basically kills the productivity of the bot once more than two people are on at the same time (yes, it's pretty bad). So, in case that feature works the way I think it does, is there a way to turn it off? If it works differently from how I think it works, how does it work?

**Comment by MrKinau** [comment]
This feature will fix issues. If the fishing bobber isnt thrown correctly or the server havent recognized it  the bot tries to re-throw it. This may also happen if you using the bot with an unenchanted (no Lure, Luck of the sea) fishing rod. The re-throw should be almost immediately after getting back the bobber (I think its currently not working that way and waiting 60 seconds before it). I will mark it as bug and could also add an config update to disable it.
