### ISSUE TITLE
Could not receive packet! Shutting down... 

### ISSUE THREAD

**Issue by sky5416841** [MrKinau/FishingBot#207]
Server is 1.19.2  I have open Spoof forge 

![image](https://github.com/MrKinau/FishingBot/assets/109945433/7b7a5e27-8e30-4685-94e4-0c00ba53c90b)

When I close Spoof forge 

Like this [2023-06-19 05:04:26] [SEVERE ] Login failed: {"text":"This server has mods that require Forge to be installed on the client. Contact your server admin for more details."} 

Is any problem

**Comment by MrKinau** [comment]
Forge spoofing only works without mods (if it even works, I guess the amount of people still using Forge nowadays is quite small)
See: https://github.com/MrKinau/FishingBot/issues/38
