### ISSUE TITLE
[Request] Please add Alt Account login option

### ISSUE THREAD

**Issue by iegl3** [MrKinau/FishingBot#216]

**Comment by MrKinau** [comment]
No. I won't to support the usage of (cracked/hacked/shared) alt accounts.

**Comment by iegl3** [comment]
why tho

**Comment by MrKinau** [comment]
Alt accounts are either hacked accounts from other users and I do not support stealing credentials, but even if they are legitimately purchased, they are 99% used for bypassing bans.
