### ISSUE TITLE
Add an option every 2-3 minutes it goes side from side

### ISSUE THREAD

**Issue by 4omak** [MrKinau/FishingBot#23]
If possible could you add a feature where if will move left or right every 2-3 minutes, the servers i play on all have some sort of anti afk fishing plugins and so they prevent fishing from the same spot every like 3 minutes or so

**Comment by MrKinau** [comment]
Thank you for your suggestions, but the bot is not inteded to bypass Anti-AFK techniques. If you want such feature you have to code it at your own. Sorry.
