### ISSUE TITLE
rat

### ISSUE THREAD

**Issue by Benjamacs1** [MrKinau/FishingBot#241]
when I looked threw the bot it showed multiple suspicious things such as token grabbers/loggers etc. please explain

**Comment by MrKinau** [comment]
Please be free to point out, which parts of the code looks "suspicious" or like a "token grabbers/logger" and I'll explain you what's the code for

**Comment by Benjamacs1** [comment]
okie dokie
1s

**Comment by Benjamacs1** [comment]
this is kinda weird


package systems.kinau.fishingbot.auth;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.UUID;

@RequiredArgsConstructor
@ToString
public class AuthData {

    **@Getter private final String accessToken;
    @Getter private final String uuid;
    @Getter private final String username;
    @Getter @Setter private ProfileKeys profileKeys;**

    @RequiredArgsConstructor
    @Getter
    public static class ProfileKeys {
        private final PublicKey publicKey;
        private final String publicKeySignature;
        private final PrivateKey privateKey;
        private final long expiresAt;
        private final UUID chatSessionId = UUID.randomUUID();
    }
}

I bolded the code that I think is suspicious and there is more but I have to find it again

**Comment by Benjamacs1** [comment]
no sorry this is the party of the code

**@Getter private final String accessToken;
@Getter private final String uuid;
@Getter private final String username;
@Getter @Setter private ProfileKeys profileKeys;**

**Comment by MrKinau** [comment]
The [AuthData](https://github.com/MrKinau/FishingBot/blob/main/src/main/java/systems/kinau/fishingbot/auth/AuthData.java) you are referring to is an object used to store the minecraft credentials. It is filled with either bogo values if offline mode (cracked) is selected or with the accessToken which is retreived by the [MSAuthenticator](https://github.com/MrKinau/FishingBot/blob/main/src/main/java/systems/kinau/fishingbot/auth/MicrosoftAuthenticator.java) or the [OneSixAuthenticator](https://github.com/MrKinau/FishingBot/blob/main/src/main/java/systems/kinau/fishingbot/auth/OneSixAuthenticator.java) (if used in MultiMC/Prism).
The data is not send to any remote server, it remains on your device (in memory). Every other parts of the data is the current minecraft user UUID, the minecraft user name, the RSA Keys used for chat signing. If you have any questions about these feel free to ask.

**Comment by MrKinau** [comment]
> The [AuthData](https://github.com/MrKinau/FishingBot/blob/main/src/main/java/systems/kinau/fishingbot/auth/AuthData.java) you are referring to is an object used to store the minecraft credentials. It is filled with either bogo values if offline mode (cracked) is selected or with the accessToken which is retreived by the [MSAuthenticator](https://github.com/MrKinau/FishingBot/blob/main/src/main/java/systems/kinau/fishingbot/auth/MicrosoftAuthenticator.java) or the [OneSixAuthenticator](https://github.com/MrKinau/FishingBot/blob/main/src/main/java/systems/kinau/fishingbot/auth/OneSixAuthenticator.java) (if used in MultiMC/Prism). The data is not send to any remote server, it remains on your device (in memory). Every other parts of the data is the current minecraft user UUID, the minecraft user name, the RSA Keys used for chat signing. If you have any questions about these feel free to ask.

To be more exact: parts of the data is shared with the specified server to be able to connect to it (e.g. username, uuid, chat keys)
