### ISSUE TITLE
Support neoforge spoofing

### ISSUE THREAD

**Issue by Bluzombie911** [MrKinau/FishingBot#243]
Trying to get this on a neoforge server but doesn't work since it isn't supported.

**Comment by MrKinau** [comment]
Forge support is currently very limited (if it still works at all), as some Forge/Neoforge mods require special handshakes it won't be implemented any time soon. According to some users fabric seems to be somewhat supported (although I haven't really tested it, it just works out of the box). Therefore as long as it does not work out of the box, it won't be supported at least I am not interested in supporting it (if it is possible), but I am willing to accept PRs regarding Forge/NeoForge support as long as it does not break vanilla.
For more detail regarding Forge see #38
