### ISSUE TITLE
FishingBot v2.12.4 - Starting fishing

### ISSUE THREAD

**Issue by bertocaster** [MrKinau/FishingBot#248]
Hi Mr Kinau,

The bot announces in that that the fish bot is starting to fish. This is despite disabling announcements. Would appreciate if the bot does not announce anything when starting to fish.

Thank you!

**Comment by MrKinau** [comment]
Hey @bertocaster 

You can disable all announcements in the Settings. The announcement about caught items and level ups can be configured/disabled in the Announcements section. The start text you mentioned can be configured/disabled in the Start actions section. Hope this helps, if you need any more help, feel free to ask :)

**Comment by bertocaster** [comment]
Thanks boss, I missed that one. My bad!
