### ISSUE TITLE
can the bot use chat? 

### ISSUE THREAD

**Issue by berkedoga27** [MrKinau/FishingBot#25]
im playing on a server we have to log in but i cant log in with bot

**Comment by MrKinau** [comment]
I'm not sure if I've fully understood you.

You want the bot to execute a command on startup like `/login <password>`?

If you want so, you can change the start-text, in the config file. You can type any text and commands there seperated by semicolon.
Alternatively you can enable the proxy-chat, where you can write commands or chat messages in the console of the bot.

Hope this helps you :)

**Comment by berkedoga27** [comment]
yes that but i also want it to type /survival
so i want 2 start text can it happen

**Comment by berkedoga27** [comment]
oh i got it so i type /login asd123; /survival?

**Comment by MrKinau** [comment]
correctly :)
