### ISSUE TITLE
can you update to 1.15.2

### ISSUE THREAD

**Issue by berkedoga27** [MrKinau/FishingBot#26]
can you update to 1.15.2 please

**Comment by MrKinau** [comment]
Oh Well, havent recognized this version ist already out. I will commit an update today. Thanks for mentioning

**Comment by MrKinau** [comment]
Well there was no protocol changes so the latest version for 1.15.1 still worked. Just added the version to avoid the message `This server is not running a supported protocol version: ProtocolVersion 578`
