### ISSUE TITLE
add auto-command

### ISSUE THREAD

**Issue by itor4589** [MrKinau/FishingBot#30]
When I disconnect, I have to login again
I want to add auto-command. . .
ex. auto-reconnect-command

**Comment by MrKinau** [comment]
I am nopt sure what you want :/

Commands to be executed by the bot on reconnect? You may try the start-text option in the config

Commands in the bot console? Which commands do you want? Please explain more precisely what you want

**Comment by itor4589** [comment]
if bot disconnect
when re-connect, i need “/login <pass>“ auto
.
//server use authme for login (offline-mode)
//Sorry for bad end

**Comment by MrKinau** [comment]
Have you tried writing these commands in the start-text config option?

**Comment by itor4589** [comment]
Yes it works
but, It executes command 2 times
It show the password in console

**Comment by MrKinau** [comment]
So your problem is that the start-text will be executed twice and should be hidden in the console?

**Comment by itor4589** [comment]
yes, 
server :
login -> start-text => run command
if success login -> survival => run command a again (no authme /login show password in console admin)

**Comment by MrKinau** [comment]
fixed in latest release
