### ISSUE TITLE
Can you update it to SnapShots or tell me how to add a new protocol?

### ISSUE THREAD

**Issue by RootRobo** [MrKinau/FishingBot#31]

**Comment by MrKinau** [comment]
Thanks for your interest.

I will only push protocol updates if the release versions are published. I tried to push in snapshots, but there are too many changes which I dont want to handle. Therefore almost directly after the 1.16 release an update will follow. The bot always tries to connect to the server with the latest protocol version, but in major releases the packet numbers and/or the packet content differs. Updating is quite easy (If there are no big packet changes in the used packets). You can look in the latest uodate commit to lookup how it works. All new packet numbers are documented at wiki.vg under pre-release. Have fun working at it and feel free to contribute.

**Comment by RootRobo** [comment]
At first thanks a lot for your fast reply! I'll try to use it on a 20w11a server and hope it works, If not, I'll try to update it to the Snapshot (and if its successful I will contribute)
