### ISSUE TITLE
Cant import source code in IntelliJ IDEA correctly

### ISSUE THREAD

**Issue by RootRobo** [MrKinau/FishingBot#33]
I can't import the source code in IntelliJ IDEA and almost every class is full of errors such as:
```
Cannot resolve method 'getInstance' in FishingBot
Cannot resolve method 'getConfig' in FishingBot
```
and so on, but compiling and running works fine. Also it show this warning while compiling etc:
```
Some problems were encountered while building the effective model for systems.kinau:FishingBot:jar:1.0-SNAPSHOT
'dependencies.dependency.version' for com.flowpowered:flow-nbt:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 64, column 22
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.
```
I really do not know what I did wrong, this is the first time I used Maven. It would be really nice if someone could help me. (Also sorry for my bad english, I am from Germany)

**Comment by MrKinau** [comment]
This project uses lombok, which allows me to use @Getter @Setter and so on annotations. You have to install the lombok plugin in IntelliJ to remove the errors.

The NBT API is quite outdated, but works afaik.

---
Für das Projekt habe ich Lombok benutzt, was im Prinzip dafür sorgt, dass @Getter @Setter usw. Annotationen verwendet werden können. Du musst Lombok als Plugin zu IntelliJ hinzufügen, damit diese Annotationen richtig von IntelliJ interpretiert werden können und keine Errors angezeigt werden.

Die NBT API ist relativ veraltet und sollte eig. mal ausgetauscht werden aber sie funktioniert afaik noch.

**Comment by MrKinau** [comment]
well these mentions was not wanted behaviour

**Comment by RootRobo** [comment]
Thank you!

**Comment by RootRobo** [comment]
Now I get a question:
`Lombok Requires Annotation Processing: Do you want to enable annotation processors? Enable
`
Do I have to enable this?

**Comment by MrKinau** [comment]
yes

**Comment by RootRobo** [comment]
Okay, thank you!
