### ISSUE TITLE
Command To empty Inventory

### ISSUE THREAD

**Issue by riyadsy** [MrKinau/FishingBot#36]
It would be much easier to allow the bot to empty it's inventory on command so the other player can just pick the items up. Empty its inventory as in pressing "ctrl" and "Q" on every inventory slot (except the fishing rod equipped).

**Comment by MrKinau** [comment]
Not sure if it will get implemented, but I will try my best to get it in the next milestone

**Comment by MrKinau** [comment]
After a long time, it got implemented, sry for the long delay.
