### ISSUE TITLE
Please add atributes to jar file

### ISSUE THREAD

**Issue by Johnson070** [MrKinau/FishingBot#37]
Can you please add the transfer of attributes to the jar file it will be very useful.

For example, pass the file path with config or pass attributes without a file.

**Comment by RootRobo** [comment]
Yes, this could be very useful if you want to have multiple instances running in one directory.

**Comment by MrKinau** [comment]
definitely useful, thanks for your isssue. Will be implemented with several useful startup arguments

**Comment by MrKinau** [comment]
implemented in https://github.com/MrKinau/FishingBot/releases/tag/2.7.6
sry for the huge delay :/
