### ISSUE TITLE
CMD errors

### ISSUE THREAD

**Issue by OwenKelly05** [MrKinau/FishingBot#40]
Hello and sorry im not sure if I'm doing this wrong but I download Fishingbot.jar and use cmd and type java -jar Fishingbot.jar and I get a ton of Warnings and I dont know how to fix it.
![Problem](https://user-images.githubusercontent.com/63629155/79186206-dbf11900-7dcd-11ea-9990-eacb9bf47cc1.png)

**Comment by MrKinau** [comment]
The warnings are normal. At the first start the bot generates at it's directory a new file called config.properties Where you can set your login credentials and customize the features

**Comment by OwenKelly05** [comment]
How to I open the config file to edit it?

**Comment by MrKinau** [comment]
Is this a joke? You can use any editor of your choice
