### ISSUE TITLE
Command-line flag to specify config file?

### ISSUE THREAD

**Issue by sudofox** [MrKinau/FishingBot#43]
Is there any way to pass a specific config file to the bot? I've built a large fishing complex with thousand of chests and it's been lagging my computer like mad to run many instances of Minecraft. Thus, I need to be able to spawn the bot with a number of different configs.

I can't seem to find usage details about how to specify which config file to load, though.

**Comment by MrKinau** [comment]
It's planned, but currently not available (see #37)

**Comment by sudofox** [comment]
Alrighty-o. Looking forward to it. In the meantime I shall kludge it by duplicating the jar across directories or maybe dusting off Eclipse and hacking in the functionality.

![image](https://user-images.githubusercontent.com/3847441/79680363-db48f000-81dc-11ea-8f94-a7764e82d81d.png)
