### ISSUE TITLE
Auto-select fishing rod from inventory when available

### ISSUE THREAD

**Issue by sudofox** [MrKinau/FishingBot#46]
I've been having an odd issue where sometimes a mending rod will break (maybe the bot gets stuck or something.) However tossing it another fishing rod doesn't seem to make it autoselect the rod unless the currently selected hotbar slot happens to be the one with the rod in it, which can only be changed as an actual player.

Would be great if it could automatically pull rods from the inventory in certain conditions, such as if it fishes or picks up a better rod than the one it's currently using.

Here is a mod with a reference implementation of the "select better rod" functionality: [AutoFish](https://github.com/Wurst-Imperium/Wurst7/blob/d2cc045d62f9d914fb13b778ec6c0cd51aec2cbe/src/main/java/net/wurstclient/hacks/AutoFishHack.java )

**Comment by MrKinau** [comment]
sounds great, but it's weird that your mending tools break? Does the bot collect the xp orbs? There was a bug, that the bot does not collect the xp orbs (they were flying around the player, but were not collected, because of missing position updates), but I think this got fixed already.
The "equip better rod" is definitely useful and will be implemented (maybe in the next milestone)

**Comment by sudofox** [comment]
I don't know why the rods didn't mend - some of them clearly are mending just fine - but I've had that same issue happen when running autofish on a real client in the past. Not sure how it happens but maybe the orbs are getting collected by a different player? I have several of my accounts lined up next to each other about one block apart from each other.

I'm fine with just giving them a bunch of enchanted rods - not like there's any shortage of them from all the stuff being fished up. I can also spread the fishers out further from each other as more fishing room modules are built, we have about five so far.

![image](https://user-images.githubusercontent.com/3847441/79904084-208a3f00-83e2-11ea-9441-162e824dd90b.png)

**Comment by MrKinau** [comment]
a long time ago, it finally got implemented, lol
