### ISSUE TITLE
How much computing power does this need

### ISSUE THREAD

**Issue by SJS830** [MrKinau/FishingBot#47]
I was planning to run this script on a lightsail instance. What specs it would run on?

**Comment by MrKinau** [comment]
There should not be a problem using it on a lightsail instance (not tested)

I am using multiple bots parallel on a raspi 2B.
One bot uses about 50MB RAM and up to 2% of the CPU

![image](https://user-images.githubusercontent.com/13185260/79863083-71e10100-83d7-11ea-84d9-33e68afceedf.png)
