### ISSUE TITLE
Error at ClientDefaultsModule

### ISSUE THREAD

**Issue by Coie0** [MrKinau/FishingBot#49]
I get the following error when trying to start the bot.
[2020-04-28 16:58:11] [INFO   ] Module "ClientDefaultsModule" enabled!
[2020-04-28 16:58:12] [SEVERE ] Login failed: {"extra":[{"text":"Not authenticated with "},{"clickEvent":{"action":"open_url","value":"http://Minecraft.net"},"text":"Minecraft.net"},{"text":""}],"text":""}
[2020-04-28 16:58:12] [INFO   ] Module "ClientDefaultsModule" disabled!
![Capture](https://user-images.githubusercontent.com/26350823/80510477-741cff80-8983-11ea-9cc8-6b3e312e00d6.PNG)

**Comment by MrKinau** [comment]
Your minecraft account is not correctly authenticated with Minecraft.net
The server checks with the Mojang API if the client IP is the same which authenticated before. On legit minecraft account you shouldnt get this message unless:

1. Your session is invalid (You received a new IP between auth and connect) (should be impossible in only 1 second)
2. Your account is not authenticated with Minecraft. (should be impossible, the bot only uses Mojang)
3. The server you try to connect randomly kicks you with this message. (weird)
4. The sessionservers are down (I think it's the session server) and the server can't test if your account is legit authenticated (Yes they are currently down)

**Comment by Coie0** [comment]
Yeah, that must have been it. It works now, thanks.
