### ISSUE TITLE
Fishing bot [feature request]

### ISSUE THREAD

**Issue by Quarantene** [MrKinau/FishingBot#50]
Hi, I was just wandering around looking for bots, and I was wondering if you would be able to add a function to fish for pixelmon. I know it's a forge mod, but I was just wondering if that would work. It goes off the system whereby it uses exclamation to indicate the catch and the amount of exclamation marks (1-3) indicates the level of catch. It drops important items, and the encountering of pokemon can be avoided with a fainted pokemon in the team. So I was just wondering if it would be possible? # #

**Comment by MrKinau** [comment]
Everything a normal player can do would be possible.
As the target group of this feature is quite small, I will not spend my time of doing this. In the next release I try to bypass the forge handshakes to allow joining on modded servers, but there will be no other implementation of modded fishing mechanics, but you are free to create a fork.
