### ISSUE TITLE
Cast Exception

### ISSUE THREAD

**Issue by Richiewoohoo** [MrKinau/FishingBot#51]
When I run the program I get this error:

exception in thread "main" java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
     at com.google.gson.JsonObject.getAsJsonObject (JsonObject.java:205)
     at systems.kinau.fishingbot.network.ping.ServerPinger.ping (ServerPinger.java:80)
     at systems.kinau.fishingbot.fishingbot.<init>(Fighingbot.java:133)
     at systems.kinau.fishingbot.Main.main(Main.java:13)

**Comment by MrKinau** [comment]
Which server address is in your config.properties?

**Comment by Richiewoohoo** [comment]
mc.hypixel.net

heh.

**Comment by MrKinau** [comment]
weird. Having the default config (using 1.8 to join) everything works fine while testing it?

**Comment by Richiewoohoo** [comment]
I'll try using 1.8 first. I'll update you if anything happens.

**Comment by Richiewoohoo** [comment]
Alright so I used 1.8 and it works. The problem is I have to switch to
another minigame server in hypixel. I guess that can't be helped then.
Thank you!

**Comment by MrKinau** [comment]
I am not sure if hypixel has commands for it or special domains to instantly join a lobby, but you can use commands in the start-text config option

**Comment by Richiewoohoo** [comment]
I'll test it out, but it most likely isn't a problem on your end. thanks
again!
