### ISSUE TITLE
Show log in discord

### ISSUE THREAD

**Issue by hsiang051** [MrKinau/FishingBot#53]
![image](https://user-images.githubusercontent.com/41193849/83326589-ded59980-a2a7-11ea-8fa0-5d350cbcff4a.png)
![image](https://user-images.githubusercontent.com/41193849/83326610-0462a300-a2a8-11ea-8909-c6fdea4e2316.png)

I hope you can pass the fishing log to discord for easy viewing.

**Comment by MrKinau** [comment]
I'm not quite sure what you want? What have you done and whats your problem with it?
