### ISSUE TITLE
Exception when attempting to join Realms as of 1.16.1

### ISSUE THREAD

**Issue by Shaman-Infinitus** [MrKinau/FishingBot#54]
Hello, I am encountering an error when attempting to connect the bot to a Realm in Minecraft version 1.16.1. Here is what the console reads:

```
Try to authenticate email@address.com:****************
Authentication successful!
Accepted TOS!
Connecting to: {"address":"52.154.64.212:31834","resourcePackUrl":null,"resourcePackHash":null}
Pinging 52.154.64.212:31834 with protocol of MC-1.8
Exception in thread "main" systems.kinau.fishingbot.network.utils.InvalidPacketException: VarInt too big
at systems.kinau.fishingbot.network.protocol.Packet.readVarInt(Packet.java:112)
at systems.kinau.fishingbot.network.ping.ServerPinger.ping(ServerPinger.java:66)
at systems.kinau.fishingbot.FishingBot.<init>(FishingBot.java:143)
at systems.kinau.fishingbot.Main.main(Main.java:11)
```

Even though `config.properties` indicates that it is not necessary for Realms, I attempted to solve the issue by changing the protocol to 1.16.1, which resulted in an identical error message except for the protocol being `MC-1.16.1`.

I performed the initial setup of the bot for Realms as guided; the console was able to find the ID of my Realm, which I entered into `config.properties`. For reference, here is my `config.properties` configuration:

```
auto-disconnect-players-threshold=5
announce-type-chat=NONE
auto-disconnect=false
log-packets=false
log-count=15
server-port=25565
default-protocol=1.16.1
proxy-chat=false
auto-reconnect=true
announce-type-console=ALL_BUT_FISH
announce-lvl-up=false
server-ip=127.0.0.1
stucking-fix-enabled=true
auto-reconnect-time=3
account-password=****************
start-text-enabled=true
realm-id=********
online-mode=true
account-username=email@address.com
discord-webHook=false
realm-accept-tos=true
start-text=%prefix%Starting fishing;/trigger Bot
```

**Comment by MrKinau** [comment]
Thanks for your issue I will look after it. Maybe its just just a problem with the protocol version id which changed in 1.16.1 and the bot trying to connect with the old 1.16 version (havent updated yet).

**Comment by MrKinau** [comment]
Figured out I can't find any account which havent used the free realm. I can't test it without. Can you please write me an E-Mail to d@vid.codes or just invite the account Leve19 to your realm? Otherwise I can't test whats wrong with realms :/

**Comment by Shaman-Infinitus** [comment]
Sure thing. I started a trial realm on one of my accounts specifically for testing, so you can log into it and do whatever you need. I've invited Leve19 and given them operator permission. Let me know if you need additional accounts invited.
