### ISSUE TITLE
Fishing akf bot for minecraft

### ISSUE THREAD

**Issue by HappyCryingCat** [MrKinau/FishingBot#58]
Hi so I typed in the thing into cmd to start the client, and I get a message saying it cant access the file. The file is in downloads, when i type dir it says its there, and I ran the cmd thing as administrator but it still says its unable to access it. Any yes I extracted the file before all this. What am I doing wrong?

**Comment by MrKinau** [comment]
Please carefully follow the instructions

1. Download a [release ](https://github.com/MrKinau/FishingBot/releases/)(or build it at you own)
2. Start the Client (java -jar Fishingbot.jar)
3. Fill in the config.properties, which generated on the first start
4. Give a fishing rod to the account you used and place him in front of water (remember you can only fish treasure in open water)

You do not have to extract anything.
