### ISSUE TITLE
Include a realtime log catcher with the bot

### ISSUE THREAD

**Issue by DreaMReapeR88** [MrKinau/FishingBot#60]
It's not that big of a deal to do if you're using unix, but in windows it is a bit harder.
I did it by creating a quick powershell line: "Get-Content ***logs directory***\log0.log -wait"
Pretty sure you need the tail command for win32 though, i had it installed before.
This way you can see what the bot catches and when it levels up real time, and it's also easier to know if it got stuck or something happened like a mob managed to find it's way to the fishing place.

Great work with the bot! l love it!

**Comment by MrKinau** [comment]
Thanks for your issue,

I'm sadly pretty unsure what you are meaning? How do you start the bot? The bot prints everything you specified in the config to the console as well as to the log file.

And thanks for your feedback :)

**Comment by DreaMReapeR88** [comment]
I don't seem to know how to open the console, i mean usually I just launch the java executable and it just appears as a running task in task manager, no console/GUI pops up. This was basically a work around specifically because I never get the console to appear.

This is how it shows up to me: [https://ibb.co/9pML4Sy](url) (also included the way i do the alternate realtime log catcher)
Am I doing anything wrong? Am I supposed to start the executable in a different way?

**Comment by MrKinau** [comment]
on windows the common way is to Open a powershell at the dir of the jar (shift-rightclick -> open powershell here) and then start the bot with java -jar FishingBot-<Version>.jar or alternatively create a batch-script that does the same similar to Spigot start scripts

**Comment by DreaMReapeR88** [comment]
Alright! thanks a bunch for letting me know of this way easier method.
Again, great work on the fishing bot! definitely the best I've seen so far and the easiest to use.
