### ISSUE TITLE
Joinable Realms?

### ISSUE THREAD

**Issue by nothinglive** [MrKinau/FishingBot#62]
Hello! I downloaded the bot and everything works fine, except that it only returns realm IDs for the realm I own, and not realms I am a member of. Is there a way to get these IDs?

**Comment by MrKinau** [comment]
Well the bot uses the /worlds endpoint of the Realms API ([here](https://wiki.vg/Realms_API#GET_.2Fworlds)), as described it should list the realms you own and that ones you've got an invitation to. In the past it worked for every realm you could join (Means you have to accept the invitation manually before you are able to join). If you are still unabe to list all realms, you could invite the account Leve19 to a realm (so I can take a closer look at it if it changed somehow)

**Comment by MrKinau** [comment]
As you havent answered it seems to be fixed. If not, open a new issue.
