### ISSUE TITLE
Alert when player gets attacked

### ISSUE THREAD

**Issue by maxswjeon** [MrKinau/FishingBot#69]
From 1.16, AFK fishing farms in indoors are banned. Well, not banned, but the bobber seeks the near 5x4x5, and does not catch up if the blocks are water or air.

Reference: https://minecraft.gamepedia.com/Fishing#History

|Version | Update|
|---------|---------|
|20w12a | Treasure can now be obtained only through fishing in open water. Open water is defined as a 5×4×5 area around the bobber, in which only air, water source blocks, or waterlogged blocks without collision can be present. Bubble columns and lily pads both invalidate open water. |
|20w13a | Open water is now calculated differently. Each layer in the area around the bobber is checked, and each layer must have only air or water (or similar). Bubble columns no longer invalidate water layer checks and lily pads no longer invalidate air layer checks. |

During the AFK fishing, I was attacked and killed by a phantom. I almost lost all my items. (including enchanted fishing rod)

Therefore, I suggest these new features.

1. Alert when attacked
Alert by discord or console when the player gets attacked.

2. Alert when respawning
Alert by discord or console when the player respawns.

3. Execute a predefined command at a certain amount of health
The player can escape to home if the server supports '/home' command or tp to certain places

4. Execute a predefined command after the player respawns
The player can move to the fishing spot after respawning at the spawn place (spawn place may be predefined at some servers and may support returning to the previous places with the command '/back')

**Comment by MrKinau** [comment]
Thanks for you issue, I'll list them as planned features, but it might take a while for themn to get implemented, because I am quite busy and there are lots of other planned features.

**Comment by MrKinau** [comment]
implemented in the latest release
