### ISSUE TITLE
Bot stops fishing when changing difficulty to Hard

### ISSUE THREAD

**Issue by Tragafantas** [MrKinau/FishingBot#71]
I have tested this on my localhost, I don't know if that's the issue, whenever I change the difficulty to Hard it stops fishing, but when I change it to Peaceful it starts again. Should this be counted as an issue?

https://imgur.com/a/TxEYm7h

**Comment by MrKinau** [comment]
Thanks for your issue,

indeed this is a bug, which happens, because the SetDifficultyPacket is used to start the fishing progress, because it is sent on join. So if it is sent twice the bot tries to restart fishing and fails. I will fix this bug asap, thanks for reporting it.

**Comment by MrKinau** [comment]
the bug should be fixed in the latest release, I've updated the [2.7.6 release](https://github.com/MrKinau/FishingBot/releases/tag/2.7.6). If you find more bugs or want to request feature feel free to open another issue :)
