### ISSUE TITLE
Phishing attempt?

### ISSUE THREAD

**Issue by VertiGoox** [MrKinau/FishingBot#72]
Is this just a scam that change your MC password?

**Comment by MrKinau** [comment]
yes

**Comment by Summerfeeling** [comment]
definitely

**Comment by VertiGoox** [comment]
What's the point?

**Comment by MrKinau** [comment]
It's open source, read the code and if you are too paranoid you can build it yourself. It's just a Fishing Bot. nothing else

**Comment by VertiGoox** [comment]
Cool, then why, as I logged, it changed my MC password?

**Comment by VertiGoox** [comment]
(Not a programmer)

**Comment by MrKinau** [comment]
> Cool, then why, as I logged, it changed my MC password?

I do not think this is one core-functionality of a Fishing Bot, huh?

**Comment by MrKinau** [comment]
If it seems that you credentials are wrong after using the bot it could be Mojang temp-ban, because of too many login-attempts

see: https://github.com/MrKinau/FishingBot/wiki/Troubleshooting#login-failed-translatemultiplayerdisconnectoutdated_clientwith1162

**Comment by VertiGoox** [comment]
Ok, tanks for the answer.

**Comment by VertiGoox** [comment]
What does this error means?

[2020-09-06 05:19:00] [SEVERE ] Login failed: {"translate":"multiplayer.disconnect.outdated_client","with":["1.16.2"]}

**Comment by MrKinau** [comment]
see: https://github.com/MrKinau/FishingBot/wiki/Troubleshooting#login-failed-translatemultiplayerdisconnectoutdated_clientwith1162

**Comment by VertiGoox** [comment]
If I log-on a server with no port, what should I put in the port section?

For example, the IP of the server I join is example.world

**Comment by MrKinau** [comment]
server-port=25565

**Comment by VertiGoox** [comment]
[2020-09-06 05:24:46] [INFO   ] Pinging example.world:25565 with protocol of MC-1.6.2 
[2020-09-06 05:24:46] [SEVERE ] Could not ping: example.world

**Comment by MrKinau** [comment]
The Minecraft Version 1.6.2 is not supported. Maybe you are trying to target 1.16.2?

**Comment by VertiGoox** [comment]
Yes, maybe I'm retarded and I mistook 1.6.2 to 1.16.2...
