### ISSUE TITLE
1.16.3 Bug

### ISSUE THREAD

**Issue by VertiGoox** [MrKinau/FishingBot#74]
Sup,

Updated client and server to 1.6.3, show this error code:

[2020-09-11 05:43:05] [SEVERE ] Login failed: {"translate":"multiplayer.disconnect.outdated_client","with":["1.16.3"]} 

Client and server are running on 1.16.3, bot config set up on 1.6.3.

**Comment by MrKinau** [comment]
Thanks for your issue.

1.16.3 is currently not supported. I'll working on it for now. (btw 1.6.3 is not 1.16.3)

**Comment by VertiGoox** [comment]
Yes.

**Comment by MrKinau** [comment]
1.16.3 support added in latest release ( https://github.com/MrKinau/FishingBot/releases/tag/2.7.7 )

Thanks for your reminder

**Comment by VertiGoox** [comment]
Thanks for your support
