### ISSUE TITLE
Adding /login <password> option for online-mod= false servers

### ISSUE THREAD

**Issue by derintpdmr** [MrKinau/FishingBot#76]
I have been playing on a server which uses authme plugin. Each time when the bot joins the server it has to write /login <password> on chat. The password is decided by players. So if there will be a option to write authme password in config, that will be so nice.

I changed start-text in config to /login <password> command but when the bot gets kicked from being idle, it doesn't put start-text on the chat.

**Comment by MrKinau** [comment]
Thanks for your issue.
This, indeed, is a bug. The start-text should be executed every time the bot connects (also on reconnect after timeout).
I'll put it on the ToDo-List.
