### ISSUE TITLE
This but instead holding a sword and left click.

### ISSUE THREAD

**Issue by TahirMurata** [MrKinau/FishingBot#87]
I have a raid farm and want to afk it while I do other things so I thought this would be a good idea. I think you can add this in the GUI as a little feature or a complete new repository. I don't quite think this is possible but if it is I'm looking forward to it. Thank You.

**Comment by MrKinau** [comment]
I'm sorry this project is only for fishing. I do not have enough time and motivation for doing other things, but you are free to create a fork and implement such functionality :)

**Comment by DrMoraschi** [comment]
> I have a raid farm and want to afk it while I do other things so I thought this would be a good idea. I think you can add this in the GUI as a little feature or a complete new repository. I don't quite think this is possible but if it is I'm looking forward to it. Thank You.

You can check mineflayer to create bots
