### ISSUE TITLE
Default protocol

### ISSUE THREAD

**Issue by Aleksis4553** [MrKinau/FishingBot#89]
"The server is not reachable with the Minecraft version", "An unexpected error occurred: Connection refused: connect". From what I understood the default protocol is the version of Minecraft you want the bot to run in. When I changed it from 1.8 to 1.16.3 the problem keeps persisting and I don't know what to do about it.

**Comment by MrKinau** [comment]
Can you send the logs/latest.log here? (You may want to censor sensible data)

**Comment by Aleksis4553** [comment]
[log0.log](https://github.com/MrKinau/FishingBot/files/5487553/log0.log)
here's one of my logs

**Comment by MrKinau** [comment]
Seems like there is no minecraft server running with your censored ip and censored port. Have you checked if IP and port are correct? If you do not know the port set it to 25565. It would be helpful to see your config. As it seems to be an issue with the server setup in the config it might help if you leave this uncensored (You can also send it private to me DC:MrKinau#8395 or MAIL:d@vid.codes).
Without this information I can't help unless saying: Double-check your server settings
