### ISSUE TITLE
join command

### ISSUE THREAD

**Issue by PixI-bit** [MrKinau/FishingBot#91]
maybe you could add a join command that joins the server without having to go into the config and change server ip address.
Example: /join play.hivemc.com:25565

**Comment by PixI-bit** [comment]
either that or a way to edit the config within the gui

**Comment by MrKinau** [comment]
A config in the GUI and Start/Stop-Buttons are already planned features. I'll keep this issue open aslong these features are not implemented.

**Comment by MrKinau** [comment]
implemented in the latest release: https://github.com/MrKinau/FishingBot/releases/tag/2.7.14
